### ISSUE TITLE
4.1-Beer Redux-ColemanCox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#116]
## Deliverables
- [ ]  A publicly visible website (gh-pages) and link to this in your issue
## Requirements
- [ ]  Recreate the beer layout using SCSS, Bourbon, and Neat
- [x]  Use handlebars with a template to add beer items from the provided data to the DOM
- [ ]  Use `array.forEach` to iterate over the array of beer items rather than Handlebars `{{#each}}{{/each}}` loops
- [ ]  Clicking on a button on the page uses `classList` to switch between list mode and grid mode
- [ ]  Variables in `app.js` should not pollute the global scope (think self invoking anonymous functions)
- [x] Do not use jQuery - we haven't covered it so this SHOULDN'T be a problem

**Comment by rtablada** [comment]
@ColemanCox please create a pull request and link it here. Also push to GH Pages and then add that link to this issue as well.

**Comment by rtablada** [comment]
@ColemanCox missing link to GH Pages and PR link
