### ISSUE TITLE
1.2-basic-layout-Coleman Cox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#13]
- [x] a git repo containing:
  - [x] `index.html`
  - [x] `styles` folder
    - [x] `style.css`
  - [x] `images` folder
    - [x] with any images you used with your design
### Requirements
- [x]  index.html` Landing Page
- [x]  `styles/style.css` css file linked from `index.html`
- [x]  Page should have
  - [x] top image across the whole page
  - [x] badge on the left covering part of the top image
  - [x] multiple posts including different types of content using filler content
    - [x]  heading text
    - [x]  by line with author and date
    - [x]  image
    - [ ]  lorem text after the image
- [x]  Your HTML should pass in the HTML validator at [https://html5.validator.nu/](https://html5.validator.nu/)
- [ ]  Hard requirements
  - [ ] Recreate the "Never miss a post section"
    - [ ] Should have an "x" in top right
    - [x] Should stand off of the page visually
    - [ ] Should have image to the left of some stacked text
    - [x] Should have colored button
- [x]  Extra hard requirements
  - [x] Try building the left side bar where it says "the iron yard houston"

**Comment by rtablada** [comment]
@ColemanCox there is no todos listed or linked github Pull Request. Please read through http://rtablada.gitbooks.io/front-end-engineering-june-2015/content/resources/homework-startup-guide.html

If you are still having trouble with Github at least link a JSBin here so that I can see how things are coming along.

**Comment by ColemanCox** [comment]
http://jsbin.com/fayuwarova/edit?html,css,output

**Comment by rtablada** [comment]
@ColemanCox for tonight's homework focus on submitting the assignments via github and git

**Comment by rtablada** [comment]
@ColemanCox I am missing a full git repo and there is no pull request for this assignment

**Comment by ColemanCox** [comment]
git remote add origin git@github.com:ColemanCox/1.2-iron-yard-houston.git
git push -u origin master

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/1.2-iron-yard-houston

**Comment by rtablada** [comment]
@ColemanCox the repo linked is empty. I need a link to a pull request

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/1.2-layout-basic/pull/1

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/1.2-layout-basic/pull/2

**Comment by ColemanCox** [comment]
it@github.com:ColemanCox/1.2-layout-basic.git

**Comment by rtablada** [comment]
For the image, you can fix the weird surrounding by doing two things:
1. Changing your margins to 0 and width to 100%
2. Adding a rule for `body` to have no `margin`
