### ISSUE TITLE
4.4-jquery practice-ColemanCox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#138]
- [x] A repo containing at standard boilerplate with files for each mode:
### Requirements
- [ ] Todos/Plan of Attacks for each Mode
## Easy Mode

Recreate the accordion below using CSS, JavaScript, and jQuery.
### Files
- [x] `accordian.html`
- [x] `accordian.js`
- [x] `accordian.css`
### Files
- [x]  `keyboard.html`
- [x] `keyboard.js`
- [x] `keyboard.css`

Recreate the keyboard below using CSS, JavaScript, and jQuery.
Without worrying about Shift or CapsLock state.
## Hard Mode
- [ ] Add Shift and CapsLock to the keyboard

**Comment by ColemanCox** [comment]
https://github.com/TIY-LR-FEE-2015-June/assignments/pull/142

**Comment by rtablada** [comment]
@ColemanCox looks like your link here is bad, please update with PR and GH page links

**Comment by ColemanCox** [comment]
it@github.com:ColemanCox/4.4-jquery-events.git
