### ISSUE TITLE
5.4-turn based game-ColemanCox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#163]
A set of sketches (either on paper or digital) of the screens of your app
- [ ] Character Select
- [ ] Battle Screen (with attack buttons)
- [ ] Game End Screen
  - [ ]  A list of features within your Github issue broken down into small steps
  - [ ]  A full project with customized build tools to fit your project
  - [ ]  A build on Github Pages with link in your Issue
### Requirements
- [ ] No JSHint warnings or errors
- [x] There should be multiple enemy types.
- [ ] The enemy type should be randomly generated.
- [x] There should be multiple player types.
- [ ] You should be able to select the player type from a dropdown.
- [ ] The gameplay should go back and forth between an enemy and the player, each
  inflicting damage on the other when they launch a successful attack.
- [ ] The player should manually select the "Fight" action to attack.
- [ ] The enemy should automatically attack when it is its turn.
- [ ] You should use constructors and prototypes for the players and enemies.
- [ ] The player's health should be visible.
- [ ] The enemies health may be visible, at your discretion.
- [ ] After either character is killed: show a game end screen
- [ ] Attacks should have a chance of failure
## Hard Mode
- [ ] The player should be able to click "Start Over" on the game end screen
- [ ] Show damage when dealt
- [x] The player should be able to either "Fight" or "Use Magic", or some similar
  setup. Each player type should have different types of attack and/or magic. (check the `weapons` and `getAttackStrength` from our example in class)
- [ ] Give the player the ability to use items, such as items that regain health or
  increase attack.
- [ ] Make a party of players, rather than just one (a la Final Fantasy). The game
  play would cycle between Player 1 -> Enemy -> Player 2 -> Enemy, etc.
- [ ] Implement "ailments". E.g. being poisoned makes you weaker, being put to sleep
  makes you skip your turn.

**Comment by rtablada** [comment]
@ColemanCox do you have any links to PR and GH Pages and do you have some pictures of your wire frames?
