### ISSUE TITLE
5.4-turn-based-game Brent Thomas

### ISSUE THREAD

**Issue by Brent-M-Thomas** [TIY-LR-FEE-2015-June/assignments#165]
- [ ] A set of sketches (either on paper or digital) of the screens of your app
- [ ] Character Select
- [x] Battle Screen (with attack buttons)
- [ ] Game End Screen
- [ ] A list of features within your Github issue broken down into small steps
- [ ] A full project with customized build tools to fit your project
- [ ] A build on Github Pages with link in your Issue

Requirements
- [ ] No JSHint warnings or errors

Normal mode
- [x] There should be multiple enemy types.
- [ ] The enemy type should be randomly generated.
- [x] There should be multiple player types.
- [ ] You should be able to select the player type from a dropdown.
- [ ] The gameplay should go back and forth between an enemy and the player, each inflicting damage on - [ ] the other when they launch a successful attack.
- [ ] The player should manually select the "Fight" action to attack.
- [ ] The enemy should automatically attack when it is its turn.
- [x] You should use constructors and prototypes for the players and enemies.
- [x] The player's health should be visible.
- [ ] The enemies health may be visible, at your discretion.
- [ ] After either character is killed: show a game end screen
- [ ] Attacks should have a chance of failure

Hard Mode
- [ ] The player should be able to click "Start Over" on the game end screen
- [ ] Show damage when dealt
- [ ] The player should be able to either "Fight" or "Use Magic", or some similar setup. Each player type should have different types of attack and/or magic. (check the weapons and getAttackStrength from our example in class)
- [ ] Give the player the ability to use items, such as items that regain health or increase attack.
- [ ] Make a party of players, rather than just one (a la Final Fantasy). The game play would cycle between Player 1 -> Enemy -> Player 2 -> Enemy, etc.
- [ ] Implement "ailments". E.g. being poisoned makes you weaker, being put to sleep makes you skip your turn.

**Comment by Brent-M-Thomas** [comment]
<a href ="https://github.com/Brent-M-Thomas/5.4-turn-based-game/pull/1">Pull Request</a>
<a href ="http://brent-m-thomas.github.io/5.4-turn-based-game">GH page link</a>

**Comment by rtablada** [comment]
@Brent-M-Thomas link to your GH pages and wireframes?

**Comment by Brent-M-Thomas** [comment]
gh page link added.  wireframes are all on paper.

**Comment by rtablada** [comment]
@Brent-M-Thomas can you take pics of your wireframes and upload them here?

**Comment by rtablada** [comment]
It should work via drag and drop.
