### ISSUE TITLE
6.2-backbone - Coleman Cox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#168]
1. So, you're tellin' me that backbone can take say.... my character/s, their pic, and all of their different techniques and attributes, if specified as a window, or a button and render each of them where I specify?     Or am I still hung up on a character-template-type of idea?
2.  Could you sum up the thousands of words that make up that wonderfully-long encyclopedia, that is backbone, in 5 minutes?................and make ME understand it?
3. Could I use something like this...to change the "messages" part to something like

``` js
initialize: function() {
    var messages = this.collection;
    messages.on("reset", this.render, this);
    messages.on("add", this.addMessage, this);
    messages.on("remove", this.removeMessage, this);

    messsages.each(this.addMessage, this);
}
```

> "hero.collection;  
>     hero.on({{options}}) and it have the desired effect of finally getting all of my characters and such in one place?(on screen)
1.   I'm still not sure what      _.extend does         Could you review, please?

**Comment by rtablada** [comment]
We'll review the different components of Backbone and what each one does, what it is meant to do, and the terms in class today.

We'll also look at what the initialize function is and when it is run.

`_.extend` is definitely on the schedule for review
