### ISSUE TITLE
1.3-iron news-ColemanCox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#18]
- [x] A Pull request including
  - [x] `index.html`
  - [x] A linked CSS file in the location of your choice
- [x] Valid, semantic, accessable HTML
- [x] Valid CSS
- [x] At least one git commit (with a message) every hour that you're working on this project
- [x] No table layouts (you won't be able to just copy paste the HTML from hacker news)
- [ ] Hard Requirements
  - [ ] Improve the user prompts with
    - [ ] Hover states for links
  - [x] Make the different articles "zebra striped"
- [ ] Extra Hard Requirements
  - [ ] Replace the "Login" link in the nav bar with a "Account" drop down menu that has links to "Login" and "Signup"

**Comment by ColemanCox** [comment]
http://jsbin.com/qiquyiyuko/edit?html,css,output

I'm posting this here for now. I'm gonna try to finish my homework and then try the hard parts of them. I'll try to fix my github set-up if time permits.

**Comment by rtablada** [comment]
@ColemanCox you will need to make a standard homework turn in for this assignment

**Comment by rtablada** [comment]
1.3 Should be "1.3-iron-news"
