### ISSUE TITLE
6.3- Blog Comments-ColemanCox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#180]
### Deliverables
- [ ] A build on Github Pages with link in your Issue
### Requirements
- [ ] No JSHint warnings or errors
- [ ] No JSCS warnings or errors
- [ ] Separate files for views vs models vs application code
### Normal Mode
- [ ] Show button that says "add comment"
- [ ] On button click show form to create comment
  - [ ] Should ask for email, comment string, and any other fields you feel like
- [ ] Allow user to submit a comment
- [ ] Clear & hide the form after comment is sumbitted
- [ ] Show all existing comments after the "add comment" button/comment form
### Hard Mode
- [ ]  Add an up and down vote function to your comments (ala Youtube)
  - [ ] Should show blue number for up votes > down votes
  - [ ] Should show red number for down votes > up votes

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/6.3-blog-comments-/pull/1

**Comment by rtablada** [comment]
@ColemanCox missing link to GH Pages
