### ISSUE TITLE
9.1-Weather App - Coleman Cox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#219]
Deliverables
- [ ] An ember-cli project hosted on Divshot
- [ ] An Issue in the Assignments Repo
- [ ] A repo containing up to date code
- [ ] A Pull Request (or more than one) containing developed features
  Requirements
- [ ] No JSHint warnings or errors
  Normal Mode
- [ ] Create an app that uses your device/computer's geolocation, and makes a request to Forecast.io with that (lat,lng) and any search parameters.
  - [ ] Read the Forcast.io API Documentation and
- [ ] You should wireframe and design a basic layout before starting this app.
- [ ] Your app should use HTML/SCSS (with Bourbon and Neat) extensively for styling (yes this is a major part of this application) - Do not use Materialize or Bootstrap, you can use icon sets or photos from other sites.
- [ ] You should use the Ember.js Router and Routes to represent the application states. Your routes should be:
  http://localhost:4200/
  http://localhost:4200/weather/:lat/:lng
  Nightmare Mode
- [ ] In addition to Normal Mode, give your app an extra search bar that allows you to search for weather in other cities around the world.
- [ ] Use Firebase and Firebase Authentication to sign in a user and store their favorite locations

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/9.1-weather-app/pull/1

**Comment by rtablada** [comment]
@ColemanCox to create ember apps, run `ember new project-name` where you will replace `project-name` with whatever your project is named.

This will set up a new git repo in that new project as well so then you can run `hub create` and then push (then change to a `develop` branch)
