### ISSUE TITLE
04-Timeline

### ISSUE THREAD

**Issue by BrianStick** [TIY-LR-FEE-2015-June/assignments#229]
- [ ] Create a new Issue with these tasks!
- [ ] Use the `git` cli to initialize a new project
- [ ] Checkpoint: Created and committed `index.html` and `app.css` boilerplate
- [ ] Use the `hub` cli to create a repository called `04-timeline`
- [ ] Use the `git` cli to create a branch called `develop`
- [ ] In Github, open a PR _from_ `develop` _into_ `master`
- [ ] Use CDN to link to Font Awesome
- [ ] Create the markup to represent the pictured site
  - [ ] Checkpoint: Create markup to represent one item in the timeline
    - [ ] Markup: Date
    - [ ] Markup: Time
    - [ ] Markup: Icon
    - [ ] Markup: Title
    - [ ] Markup: Description
  - [ ] Checkpoint: Duplicate the first item to create multiple items to style
  - [ ] Complete: Push `index.html`
- [ ] Add styles for page
  - [ ] Checkpoint: Move Date & Time to left of Timeline
  - [ ] Checkpoint: Move Icon to Show On Top of Timeline
  - [ ] Checkpoint: Style Description and Title
  - [ ] Checkpoint: Style Arrow pointing at icon

**Comment by rtablada** [comment]
@BrianStick looks like you got the repo mixed up with the one for last semester. Here's the link over to that one instead: https://github.com/TIY-LR-FEE-2015-Fall/assignments
