### ISSUE TITLE
1.2 - Alia Borroho

### ISSUE THREAD

**Issue by rtablada** [TIY-LR-FEE-2015-June/assignments#35]
@aliaborroho I am making an issue here for your 1.2 to comment on your progress. Please make one of your own to properly turn things in.

**Comment by rtablada** [comment]
@aliaborroho it looks like you have your site working on JSBin but not saved to your github (also note that there was no link to your stylesheet in your HTML file).

**Comment by aliaborroho** [comment]
https://github.com/aliaborroho/1.2-Layout-Basic/pull/1

**Comment by rtablada** [comment]
@aliaborroho 

# Todo
- [ ] Profile pic is not loading (picture either not committed or misspelled)
- [ ] There is some room around the header image while it should reach from edge to edge and start from the top

**Comment by rtablada** [comment]
Closing in favor of #91
