### ISSUE TITLE
1.1 - Basic Git - Coleman Cox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#4]
- [x] [An issue in the class repo](https://github.com/TIY-LR-FEE-2015-June/assignments/issues/new) titled `1.1 -
  1.1-Basic Git -- {{YOUR_NAME}}` with:
  - [x] checkboxes as below under `Requirements`
- [x] A repository named `1.1-Basic Git` containing at least:
  - [x] `index.html`
- [x] A Pull Request (PR) in your `1.1-Basic Git` repo:
  - [x] _from_ branch `develop`
  - [x] _into_ branch `master`
- [x] A comment on your Issue with a link to your PR

**Comment by ColemanCox** [comment]
https://github.com/pulls?q=is%3Apr+author%3AColemanCox+is%3Aclosed

**Comment by rtablada** [comment]
@ColemanCox The main part of the site looks good for the assigned tasks.

I have noted a few small errors that are causing some issues with your link showing up (hopefully now that our text editor automatically validates our HTML, we will run in to fewer issues like this).

**Comment by ColemanCox** [comment]
I went ahead and updated 1.1 a lil to at least make it to a blue star, if
that means passable. Thanks, Ryan.   I AM gonna defeat TIY, lol.

**Comment by rtablada** [comment]
@ColemanCox you have your master and develop branches mixed up.

Let me know if you want to review git some more.
