### ISSUE TITLE
1.1-Basic Git-Alia Borroho

### ISSUE THREAD

**Issue by aliaborroho** [TIY-LR-FEE-2015-June/assignments#5]
### Deliverables
- [x] [An issue in the class repo](https://github.com/TIY-LR-FEE-2015-June/assignments/issues/new) titled `1.1 -
  Basic Git -- {{YOUR_NAME}}` with:
  - [x] checkboxes as below under `Requirements`
- [x] A repository named `1.1-Basic Git` containing at least:
  - [x] `index.html`
- [x] A Pull Request (PR) in your `1.1-Basic Git` repo:
  - [x] _from_ branch `develop`
  - [x] _into_ branch `master`
- [x] A comment on your Issue with a link to your PR

**Comment by rtablada** [comment]
@aliaborroho either move the link to your PR here or move these todos to your other issue. Just have a single one per assignment (even ones that take a few days)

**Comment by aliaborroho** [comment]
Sorry for the late response, been doing big lunches and dinners with the
family out here in Mayflower, tomorrow I will be dedicating my day to my
studies ;-)
ps:
script.js
 var myRespose= function(name){
       console.log('Im on top of it,'+"  "+ name);
};
myResponse("ryan")
};
I'm on top of it, Ryan

I know,I didn't declare my function first, so, I guess it's lost it's mojo,
ha!

Nah, seriously Ryan, I really appreciate your guidance!

-ab

**Comment by rtablada** [comment]
@aliaborroho closing this: refer to https://github.com/TIY-LR-FEE-2015-June/assignments/issues/24 instead for your 1.1
