### ISSUE TITLE
3.1 - Js Functions - Coleman Cox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#83]
### Deliverables
- [ ] Standard Homework Turn in Process
- [x] `fizzbuzz.js` file
- [x] No extra files
### Requirements
- [ ] All assertions in `fizzbuzz.js` pass
  - [ ] sum
  - [ ] sumOfArray
  - [ ] GCD
  - [ ] LCM
  - [ ] fizzbuzz

**Comment by rtablada** [comment]
@ColemanCox I need a link to a pull request. Let's set up a 1-1 to get this nailed down after lunch today. I think we can get it knocked out if we cover this just one more time.
